version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=bm0b5qenkdqmsryywkfw
      - DB_USER=uphc863xus8ue0e1
      - DB_PASSWORD=LrGrmh3bI4Iu8DbG0laf
      - DB_HOST=bm0b5qenkdqmsryywkfw-mysql.services.clever-cloud.com
      - DB_PORT=3306
